fix: command validation
418sec/curling pull request #1
Opened 2020-03-07 22:46 UTC by snoopysecurity

Fix taken from CVE-2019-10788  (https://github.com/Turistforeningen/node-im-metadata/commit/ea15dddbe0f65694bfde36b78dd488e90f246639)

Details: Checks if special characters are part of the inserted command 

NPM Test Output
```
  curl
    .run(command, cb)
{ totalSize: 0,
  received: 0,
  xferd: 0,
  averageDownloadSpeed: 0,
  averageUploadSpeed: 0,
  totalTime: 0,
  timeSpent: 3600,
  timeLeft: 0,
  currentSpeed: 0 }
      ✓ should run a command (2892ms)
    .connect(null)
      ✓ should return a connection object
    .connect(options)
      ✓ should return a connection object
    .connect({header: [], user: ""})
      .head(url, null, cb)
        ✓ should combine options in command
    .connect(options)
      .head(url, null, cb)
        ✓ should build a proper command
      .head(url, {header: string}, cb)
        ✓ should build a proper command with some args
      .head(url, {header: string, fail: null}, cb)
        ✓ should build a proper command with some args
      .head(url, {header: []}, cb)
        ✓ should build a proper command with some args
      .head(url, {H: []}, cb)
        ✓ should build a proper command with some args

  9 passing (3s)
```

2020-03-13 11:10 UTC, toufik-airane reviewed
Dear @snoopysecurity,

Thank you for your contribution.

The regexp isn't easily readable and so maintainable and especially two parts of the expression.
Can you ease the regular expression or at least document it?

Best regards.

2020-03-13 11:10 UTC, toufik-airane commented on lib/curl-transport.js
> +  if(/;|&|`|\$|\(|\)|\|\||\||!|>|<|\?|\${/g.test(command)) {
The regexp isn't easily readable and so maintainable and especially two parts of the expression.
The first part is |\|\||\| and the second is |\${.

2020-03-13 12:05 UTC, adam-nygate requested changes
Also, it looks like you're duplicating matches for `$` symbols and pipes (matching both `\|\|` and `\|`). Feel free to revise and then we can accept the PR 🙂

2020-03-13 14:24 UTC, toufik-airane commented on lib/curl-transport.js
> +  if(/;|&|`|\$|\(|\)|\|\||\||!|>|<|\?|\${/g.test(command)) {
The regexp looks similar to another contribution. 🤔

2020-03-13 23:45 UTC, snoopysecurity commented on lib/curl-transport.js
> +  if(/;|&|`|\$|\(|\)|\|\||\||!|>|<|\?|\${/g.test(command)) {
Good Point, that regex was way too complicated and un-necessary. I've changed to only block the necessary special characters needed to break an initial command. 

I do often take from other PRs and patches. This was taken from CVE-2019-10788 and CVE-2019-10787

2020-03-13 23:51 UTC, snoopysecurity commented
> Also, it looks like you're duplicating matches for `$` symbols and pipes (matching both `\|\|` and `\|`). Feel free to revise and then we can accept the PR

Good Point @adam-nygate that was a terrible regex lol. I've revised it. Please review again

2020-03-14 08:46 UTC, toufik-airane approved these changes
LGTM 👍

2020-03-16 10:47 UTC, adam-nygate approved these changes
LGTM 👍

2020-03-20 17:09 UTC, huntr-helper commented
Congratulations @snoopysecurity - your fix has been selected! :tada:<br><br>Thanks for being part of the community & helping secure the world\'s open source code.<br>If you have any questions, please respond in the comments section. Your bounty is on its way - keep hunting!

2020-03-20 17:09 UTC, merged